### ISSUE TITLE
Type Error ' embedding_provider'

### ISSUE THREAD

**Issue by AhmedAAkl** [kyegomez/PALI#1]
Great work. Many thanks for sharing it.

Actually when I tried to run the example code in example.py file
I faced this problem.

TypeError: __init__() missing 1 required keyword-only argument: 'embedding_provider'
Although I followed all the required steps as mentioned.
Any help will be appreciated.

**Comment by kyegomez** [comment]
@AhmedAAkl Hey Try again now please! I've fixed it!

If you pip installed, upgrade the package

**Comment by AhmedAAkl** [comment]
Thanks @kyegomez, it is working now. BTW the loss output is nan.

I need to reproduce your results on the VQA dataset.

I will be grateful if you shared the pretrained weights for the models.

thanks in advance.

**Comment by YilinGeStudy** [comment]
我在运行“import torch
from pali import Pali

model = Pali()

img = torch.randn(1, 3, 256, 256)
prompt = torch.randint(0, 256, (1, 1024))
mask = torch.ones(1, 1024).bool()
output_text = torch.randint(0, 256, (1, 1024))

result = model.process(img, prompt, output_text, mask)
print(result)
”时出现以下报错：
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from pali import Pali
  File "/home/PALI-main/pali/__init__.py", line 1, in <module>
    from pali.model import VitModel, Transformer, Pali
ImportError: cannot import name 'Transformer' from 'pali.model' (/home/PALI-main/pali/model.py)，原因是model.py文件中没有class transformer的内容，请问具体代码有补充和修改吗？
