### ISSUE TITLE
ImportError: cannot import name 'Transformer' from 'pali.model' (/home/PALI-main/pali/model.py)

### ISSUE THREAD

**Issue by YilinGeStudy** [kyegomez/PALI#7]
我在运行“import torch
from pali import Pali

model = Pali()

img = torch.randn(1, 3, 256, 256)
prompt = torch.randint(0, 256, (1, 1024))
mask = torch.ones(1, 1024).bool()
output_text = torch.randint(0, 256, (1, 1024))

result = model.process(img, prompt, output_text, mask)
print(result)
”时出现以下报错：
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from pali import Pali
  File "/home/PALI-main/pali/__init__.py", line 1, in <module>
    from pali.model import VitModel, Transformer, Pali
ImportError: cannot import name 'Transformer' from 'pali.model' (/home/PALI-main/pali/model.py)，原因是model.py文件中没有class transformer的内容，请问具体代码有补充和修改吗？

**Comment by kyegomez** [comment]
@YilinGeStudy Please excuse me try again!
